Ext.define('Admin.model.OrganizationInfo', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'id',
        type: 'int',
        useNull: true
    }, {
        name: 'legal_form_id',
        type: 'int',
        reference: 'Admin.model.LegalForm'
    }, {
        name: 'full_name',
        type: 'string'
    }, {
        name: 'registration_number',
        type: 'string'
    }, {
        name: 'inn',
        type: 'string'
    }, {
        name: 'kpp',
        type: 'string'
    }, {
        name: 'legal_address',
        type: 'string'
    }, {
        name: 'bank_account_number',
        type: 'string'
    }, {
        name: 'correspondent_account',
        type: 'string'
    }, {
        name: 'bank_code',
        type: 'string'
    }, {
        name: 'bank',
        type: 'string'
    }, {
        name: 'ceo',
        type: 'string'
    }, {
        name: 'chief_accountant',
        type: 'string'
    }, {
        name: 'real_address',
        type: 'string'
    }]
});
