imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  ru
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    translator: { fallback: [ru] }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - ':Form:autocomplete.html.twig'
            - ':Form:phone.html.twig'
            - ':Form:car_number_widget.html.twig'
    form_themes:
        - 'Form/fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [AppBundle, TwigBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    AppBundle: ~
                    Message:
                        type: annotation
                        dir: "%kernel.root_dir%/../src/AppBundle/Entity/Message"
                        is_bundle: false
                        prefix: AppBundle\Entity\Message
                        alias: AppBundleMessage
                    Notification:
                        type: annotation
                        dir: "%kernel.root_dir%/../src/AppBundle/Entity/Notification"
                        is_bundle: false
                        prefix: AppBundle\Entity\Notification
                        alias: AppBundleNotification
                    Billing:
                        type: annotation
                        dir: "%kernel.root_dir%/../src/AppBundle/Entity/Billing"
                        is_bundle: false
                        prefix: AppBundle\Entity\Billing
                        alias: AppBundleBilling
            em2:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    AppBundle: ~
                    Message:
                        type: annotation
                        dir: "%kernel.root_dir%/../src/AppBundle/Entity/Message"
                        is_bundle: false
                        prefix: AppBundle\Entity\Message
                        alias: AppBundleMessage
                    Notification:
                        type: annotation
                        dir: "%kernel.root_dir%/../src/AppBundle/Entity/Notification"
                        is_bundle: false
                        prefix: AppBundle\Entity\Notification
                        alias: AppBundleNotification
                    Billing:
                        type: annotation
                        dir: "%kernel.root_dir%/../src/AppBundle/Entity/Billing"
                        is_bundle: false
                        prefix: AppBundle\Entity\Billing
                        alias: AppBundleBilling

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

overblog_thrift:
    clients:
        Intergrid:
            service: OnGrid
            type: http
            hosts:
                comment:
                    host: localhost/thrift/intergrid
                    port: 80
    compiler:
        path: /usr/bin/
    services:
        OnGrid:
            definition: intergrid
            className: OnGrid
            namespace: IIT\Intergrid\Thrift
            definitionPath: app/var/thrift
            server: true
        OnGridBackend:
            definition: intergrid
            className: OnGridBackend
            namespace: IIT\Intergrid\Thrift
            definitionPath: app/var/thrift
            server: true
    servers:
        ongrid:
            service: OnGrid
            handler: app.thrift.handler.service
        ongrid_backend:
            service: OnGridBackend
            handler: app.thrift.handler.backend_service
        
gregwar_captcha:
    reload: true
    as_url: true

gregwar_image: ~

fos_rest:
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/admin/login', priorities: ['json','html'], fallback_format: json, prefer_extension: false }
            - { path: '^/admin/.+', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/admin', priorities: ['json','html'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: ['html','json'], fallback_format: html, prefer_extension: false }
    view:
        view_response_listener: force
        formats:
            json: true
            xml:  false
    routing_loader:
        default_format: json
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    body_listener: true
    access_denied_listener:
        json: true

jms_serializer:
    #visitors:
    #    json:
    #        options: [JSON_UNESCAPED_SLASHES, JSON_UNESCAPED_UNICODE]
    metadata:
        directories:
            app:
                namespace_prefix: "AppBundle"
                path: "%kernel.root_dir%/Resources/config/serializer"
                
oneup_uploader:
    mappings:
        image:
            frontend: blueimp
            namer: app.uniqid_namer
            storage:
                type: gaufrette
                filesystem: gaufrette.media_filesystem
                
knp_gaufrette:
    adapters:
        autosolutions_ssh:
            sftp:
                sftp_id: autosolutions.sftp
                directory: %kernel.root_dir%/../web/media
                create: true
        autosolutions_local:
            local:
                directory: %kernel.root_dir%/../web/media
                create: true
    filesystems:
        image:
            adapter: autosolutions_local
        media:
            adapter: autosolutions_local
            
    stream_wrapper:
        protocol: data
        filesystems:
            - image
            - media

app:
    path_resolver:
        gaufrette:
            # translate path to photo as wrapped stream and url as local to this server
            image:
                path: data://image
                url: /media
            media:
                path: data://media
                url: /media
                
lexik_jwt_authentication:
    private_key_path: %kernel.root_dir%/var/jwt/private.pem   # ssh private key path
    public_key_path:  %kernel.root_dir%/var/jwt/public.pem    # ssh public key path
    pass_phrase:      '%jwt_passphrase%'                             # ssh key pass phrase
    token_ttl:        86400                                   # token ttl - defaults to 86400
