<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160121172854 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE PAYMENT_TYPES (ID INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(150) NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CAR_SERVICES_PAYMENT_TYPES (CAR_SERVICE_ID BIGINT NOT NULL, PAYMENTS_TYPE_ID INT NOT NULL, INDEX IDX_5C75EF138A7A94FD (CAR_SERVICE_ID), INDEX IDX_5C75EF1320EE4559 (PAYMENTS_TYPE_ID), PRIMARY KEY(CAR_SERVICE_ID, PAYMENTS_TYPE_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SERVICE_TYPES (ID INT AUTO_INCREMENT NOT NULL, POST_COUNT VARCHAR(150) NOT NULL, CAR_SERVICE_ID BIGINT DEFAULT NULL, INDEX IDX_D1A263048A7A94FD (CAR_SERVICE_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SERVICE_TYPES_SERVICE_REASONS (CAR_SERVICE_TYPE_ID INT NOT NULL, SERVICE_REASON_ID INT NOT NULL, INDEX IDX_663A5344C6DC1B82 (CAR_SERVICE_TYPE_ID), INDEX IDX_663A53442C4B67CC (SERVICE_REASON_ID), PRIMARY KEY(CAR_SERVICE_TYPE_ID, SERVICE_REASON_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE CAR_SERVICES_PAYMENT_TYPES ADD CONSTRAINT FK_5C75EF138A7A94FD FOREIGN KEY (CAR_SERVICE_ID) REFERENCES CAR_SERVICES (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICES_PAYMENT_TYPES ADD CONSTRAINT FK_5C75EF1320EE4559 FOREIGN KEY (PAYMENTS_TYPE_ID) REFERENCES PAYMENT_TYPES (ID)');
        $this->addSql('ALTER TABLE SERVICE_TYPES ADD CONSTRAINT FK_D1A263048A7A94FD FOREIGN KEY (CAR_SERVICE_ID) REFERENCES CAR_SERVICES (ID)');
        $this->addSql('ALTER TABLE SERVICE_TYPES_SERVICE_REASONS ADD CONSTRAINT FK_663A5344C6DC1B82 FOREIGN KEY (CAR_SERVICE_TYPE_ID) REFERENCES SERVICE_TYPES (ID)');
        $this->addSql('ALTER TABLE SERVICE_TYPES_SERVICE_REASONS ADD CONSTRAINT FK_663A53442C4B67CC FOREIGN KEY (SERVICE_REASON_ID) REFERENCES SERVICE_REASONS (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICES ADD SITE LONGTEXT DEFAULT NULL, ADD AMOUNT_OF_CLIENTS LONGTEXT DEFAULT NULL, ADD IS_STOREHOUSE_AVAILABLE TINYINT(1) DEFAULT NULL, ADD IS_DETAIL_ORDER_AVAILABLE TINYINT(1) DEFAULT NULL, ADD WORKING_DAYS_IN_WEEK VARCHAR(255) DEFAULT NULL, ADD WAITING_PLACES_COUNT VARCHAR(255) DEFAULT NULL, ADD IS_COMFORTABLE_WAITING_PLACES_AVAILABLE TINYINT(1) DEFAULT NULL, ADD IS_FREE_WIFI_AVAILABLE TINYINT(1) DEFAULT NULL, ADD IS_HOT_DRINK_AVAILABLE TINYINT(1) DEFAULT NULL, ADD IS_FOOD_AVAILABLE TINYINT(1) DEFAULT NULL, ADD IS_ACCESS_TO_REPAIR_ZONE_AVAILABLE TINYINT(1) DEFAULT NULL, ADD IS_VISUAL_ACCESS_TO_REPAIR_ZONE_AVAILABLE TINYINT(1) DEFAULT NULL, ADD IS_VIDEO_ACCESS_TO_REPAIR_ZONE_AVAILABLE TINYINT(1) DEFAULT NULL, ADD IS_TV_AVAILABLE TINYINT(1) DEFAULT NULL, ADD IS_FREE_TRANSPORT_SERVICE_AVAILABLE TINYINT(1) DEFAULT NULL, ADD IS_REPLACEMENT_CAR_SERVICE_AVAILABLE TINYINT(1) DEFAULT NULL, ADD ADDITIONAL VARCHAR(255) DEFAULT NULL, ADD IS_GUEST_PARKING_AVAILABLE TINYINT(1) DEFAULT NULL, ADD GUEST_PARKING_COUNT VARCHAR(255) DEFAULT NULL, ADD ROAD_ZONE_IMAGE_ID BIGINT DEFAULT NULL, ADD INSPECTOR_ZONE_IMAGE_ID BIGINT DEFAULT NULL, ADD CLIENT_ZONE_IMAGE_ID BIGINT DEFAULT NULL, ADD WASHING_ZONE_IMAGE_ID BIGINT DEFAULT NULL, ADD TIRE_SERVICE_ZONE_IMAGE_ID BIGINT DEFAULT NULL, ADD BENCH_REPAIR_ZONE_IMAGE_ID BIGINT DEFAULT NULL, ADD BODY_REPAIR_ZONE_IMAGE_ID BIGINT DEFAULT NULL, ADD EMPLOYEES_IMAGE_ID BIGINT DEFAULT NULL, CHANGE WORKING_HOURS WORKING_HOURS VARCHAR(255) DEFAULT NULL, CHANGE IS_OFFICIAL IS_OFFICIAL TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE CAR_SERVICES ADD CONSTRAINT FK_EBC71FDE5AB6F15D FOREIGN KEY (ROAD_ZONE_IMAGE_ID) REFERENCES IMAGES (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICES ADD CONSTRAINT FK_EBC71FDE97669806 FOREIGN KEY (INSPECTOR_ZONE_IMAGE_ID) REFERENCES IMAGES (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICES ADD CONSTRAINT FK_EBC71FDE2E38BC54 FOREIGN KEY (CLIENT_ZONE_IMAGE_ID) REFERENCES IMAGES (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICES ADD CONSTRAINT FK_EBC71FDE34DCBD9 FOREIGN KEY (WASHING_ZONE_IMAGE_ID) REFERENCES IMAGES (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICES ADD CONSTRAINT FK_EBC71FDE27EA3A70 FOREIGN KEY (TIRE_SERVICE_ZONE_IMAGE_ID) REFERENCES IMAGES (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICES ADD CONSTRAINT FK_EBC71FDE2C1DD70A FOREIGN KEY (BENCH_REPAIR_ZONE_IMAGE_ID) REFERENCES IMAGES (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICES ADD CONSTRAINT FK_EBC71FDE3CBD645B FOREIGN KEY (BODY_REPAIR_ZONE_IMAGE_ID) REFERENCES IMAGES (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICES ADD CONSTRAINT FK_EBC71FDEFE1F9A46 FOREIGN KEY (EMPLOYEES_IMAGE_ID) REFERENCES IMAGES (ID)');
        $this->addSql('CREATE INDEX IDX_EBC71FDE5AB6F15D ON CAR_SERVICES (ROAD_ZONE_IMAGE_ID)');
        $this->addSql('CREATE INDEX IDX_EBC71FDE97669806 ON CAR_SERVICES (INSPECTOR_ZONE_IMAGE_ID)');
        $this->addSql('CREATE INDEX IDX_EBC71FDE2E38BC54 ON CAR_SERVICES (CLIENT_ZONE_IMAGE_ID)');
        $this->addSql('CREATE INDEX IDX_EBC71FDE34DCBD9 ON CAR_SERVICES (WASHING_ZONE_IMAGE_ID)');
        $this->addSql('CREATE INDEX IDX_EBC71FDE27EA3A70 ON CAR_SERVICES (TIRE_SERVICE_ZONE_IMAGE_ID)');
        $this->addSql('CREATE INDEX IDX_EBC71FDE2C1DD70A ON CAR_SERVICES (BENCH_REPAIR_ZONE_IMAGE_ID)');
        $this->addSql('CREATE INDEX IDX_EBC71FDE3CBD645B ON CAR_SERVICES (BODY_REPAIR_ZONE_IMAGE_ID)');
        $this->addSql('CREATE INDEX IDX_EBC71FDEFE1F9A46 ON CAR_SERVICES (EMPLOYEES_IMAGE_ID)');
        }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE CAR_SERVICES_PAYMENT_TYPES DROP FOREIGN KEY FK_5C75EF1320EE4559');
        $this->addSql('ALTER TABLE SERVICE_TYPES_SERVICE_REASONS DROP FOREIGN KEY FK_663A5344C6DC1B82');
        $this->addSql('DROP TABLE PAYMENT_TYPES');
        $this->addSql('DROP TABLE CAR_SERVICES_PAYMENT_TYPES');
        $this->addSql('DROP TABLE SERVICE_TYPES');
        $this->addSql('DROP TABLE SERVICE_TYPES_SERVICE_REASONS');
        $this->addSql('ALTER TABLE CAR_SERVICES DROP FOREIGN KEY FK_EBC71FDE5AB6F15D');
        $this->addSql('ALTER TABLE CAR_SERVICES DROP FOREIGN KEY FK_EBC71FDE97669806');
        $this->addSql('ALTER TABLE CAR_SERVICES DROP FOREIGN KEY FK_EBC71FDE2E38BC54');
        $this->addSql('ALTER TABLE CAR_SERVICES DROP FOREIGN KEY FK_EBC71FDE34DCBD9');
        $this->addSql('ALTER TABLE CAR_SERVICES DROP FOREIGN KEY FK_EBC71FDE27EA3A70');
        $this->addSql('ALTER TABLE CAR_SERVICES DROP FOREIGN KEY FK_EBC71FDE2C1DD70A');
        $this->addSql('ALTER TABLE CAR_SERVICES DROP FOREIGN KEY FK_EBC71FDE3CBD645B');
        $this->addSql('ALTER TABLE CAR_SERVICES DROP FOREIGN KEY FK_EBC71FDEFE1F9A46');
        $this->addSql('DROP INDEX IDX_EBC71FDE5AB6F15D ON CAR_SERVICES');
        $this->addSql('DROP INDEX IDX_EBC71FDE97669806 ON CAR_SERVICES');
        $this->addSql('DROP INDEX IDX_EBC71FDE2E38BC54 ON CAR_SERVICES');
        $this->addSql('DROP INDEX IDX_EBC71FDE34DCBD9 ON CAR_SERVICES');
        $this->addSql('DROP INDEX IDX_EBC71FDE27EA3A70 ON CAR_SERVICES');
        $this->addSql('DROP INDEX IDX_EBC71FDE2C1DD70A ON CAR_SERVICES');
        $this->addSql('DROP INDEX IDX_EBC71FDE3CBD645B ON CAR_SERVICES');
        $this->addSql('DROP INDEX IDX_EBC71FDEFE1F9A46 ON CAR_SERVICES');
        $this->addSql('ALTER TABLE CAR_SERVICES DROP SITE, DROP AMOUNT_OF_CLIENTS, DROP IS_STOREHOUSE_AVAILABLE, DROP IS_DETAIL_ORDER_AVAILABLE, DROP WORKING_DAYS_IN_WEEK, DROP WAITING_PLACES_COUNT, DROP IS_COMFORTABLE_WAITING_PLACES_AVAILABLE, DROP IS_FREE_WIFI_AVAILABLE, DROP IS_HOT_DRINK_AVAILABLE, DROP IS_FOOD_AVAILABLE, DROP IS_ACCESS_TO_REPAIR_ZONE_AVAILABLE, DROP IS_VISUAL_ACCESS_TO_REPAIR_ZONE_AVAILABLE, DROP IS_VIDEO_ACCESS_TO_REPAIR_ZONE_AVAILABLE, DROP IS_TV_AVAILABLE, DROP IS_FREE_TRANSPORT_SERVICE_AVAILABLE, DROP IS_REPLACEMENT_CAR_SERVICE_AVAILABLE, DROP ADDITIONAL, DROP IS_GUEST_PARKING_AVAILABLE, DROP GUEST_PARKING_COUNT, DROP ROAD_ZONE_IMAGE_ID, DROP INSPECTOR_ZONE_IMAGE_ID, DROP CLIENT_ZONE_IMAGE_ID, DROP WASHING_ZONE_IMAGE_ID, DROP TIRE_SERVICE_ZONE_IMAGE_ID, DROP BENCH_REPAIR_ZONE_IMAGE_ID, DROP BODY_REPAIR_ZONE_IMAGE_ID, DROP EMPLOYEES_IMAGE_ID, CHANGE WORKING_HOURS WORKING_HOURS VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE IS_OFFICIAL IS_OFFICIAL TINYINT(1) DEFAULT \'0\'');
    }
}
