<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150803151725 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE REGIONS (ID INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(255) NOT NULL, COUNTRY_ID INT DEFAULT NULL, INDEX IDX_9D2287E9CAFD65AF (COUNTRY_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE IMAGES (ID BIGINT AUTO_INCREMENT NOT NULL, PATH VARCHAR(255) NOT NULL, URL VARCHAR(255) NOT NULL, OWNER_TYPE VARCHAR(20) NOT NULL, OWNER_ID BIGINT NOT NULL, ADDED_TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SERVICES (ID BIGINT AUTO_INCREMENT NOT NULL, NAME VARCHAR(255) NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CAR_SERVICES (ID BIGINT AUTO_INCREMENT NOT NULL, NAME VARCHAR(255) NOT NULL, STREET_ADDRESS LONGTEXT NOT NULL, PHONE VARCHAR(50) NOT NULL, DIRECTOR VARCHAR(255) NOT NULL, WORKING_HOURS VARCHAR(255) NOT NULL, LOCALITY_ID INT NOT NULL, IMAGE_ID BIGINT DEFAULT NULL, COMPANY_ID BIGINT DEFAULT NULL, INDEX IDX_EBC71FDE3DCCEE9A (LOCALITY_ID), INDEX IDX_EBC71FDEC3DBFFC1 (IMAGE_ID), INDEX IDX_EBC71FDEA4494109 (COMPANY_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CAR_SERVICE_BRANDS (CAR_SERVICE_ID BIGINT NOT NULL, BRAND_ID BIGINT NOT NULL, INDEX IDX_CD537D348A7A94FD (CAR_SERVICE_ID), INDEX IDX_CD537D34BA8B0AA4 (BRAND_ID), PRIMARY KEY(CAR_SERVICE_ID, BRAND_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CAR_SERVICE_SERVICES (CAR_SERVICE_ID BIGINT NOT NULL, SERVICE_ID BIGINT NOT NULL, INDEX IDX_82DDDEFA8A7A94FD (CAR_SERVICE_ID), INDEX IDX_82DDDEFADE8EF239 (SERVICE_ID), PRIMARY KEY(CAR_SERVICE_ID, SERVICE_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE COUNTRIES (ID INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(255) NOT NULL, SHORT_NAME VARCHAR(10) NOT NULL, DOMAIN VARCHAR(5) NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE COMPANIES (ID BIGINT AUTO_INCREMENT NOT NULL, USERNAME VARCHAR(255) NOT NULL, PASSWORD VARCHAR(255) NOT NULL, SALT VARCHAR(255) NOT NULL, EMAIL VARCHAR(255) NOT NULL, SERVICE_NAME VARCHAR(255) NOT NULL, CONTACT_PERSON VARCHAR(255) NOT NULL, DESCRIPTION LONGTEXT DEFAULT NULL, PHONE VARCHAR(255) NOT NULL, DB_HOST VARCHAR(50) DEFAULT NULL, DB_PORT INT DEFAULT NULL, DB_USER VARCHAR(50) DEFAULT NULL, DB_PWD VARCHAR(50) DEFAULT NULL, REGISTRATION_DATE DATETIME NOT NULL, IS_ACTIVE TINYINT(1) NOT NULL, CONFIRMATION_TOKEN VARCHAR(255) DEFAULT NULL, BLOCKED TINYINT(1) DEFAULT NULL, IS_ONLINE TINYINT(1) NOT NULL, LAST_VISIT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, LOCALITY_ID INT NOT NULL, IMAGE_ID BIGINT DEFAULT NULL, ORG_INFO_ID BIGINT DEFAULT NULL, INDEX IDX_C686B4D53DCCEE9A (LOCALITY_ID), INDEX IDX_C686B4D5C3DBFFC1 (IMAGE_ID), INDEX IDX_C686B4D562CC2368 (ORG_INFO_ID), UNIQUE INDEX company_email_idx (EMAIL), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ORGANIZATION_INFOS (ID BIGINT AUTO_INCREMENT NOT NULL, FULL_NAME VARCHAR(255) NOT NULL, REGISTRATION_NUMBER VARCHAR(255) DEFAULT NULL, INN VARCHAR(12) NOT NULL, KPP VARCHAR(9) NOT NULL, LEGAL_ADDRESS VARCHAR(255) NOT NULL, BANK_ACCOUNT_NUMBER VARCHAR(20) NOT NULL, CORRESPONDENT_NUMBER VARCHAR(20) NOT NULL, BANK_CODE VARCHAR(9) NOT NULL, BANK VARCHAR(255) NOT NULL, CEO VARCHAR(255) DEFAULT NULL, CHIEF_ACCOUNTANT VARCHAR(255) DEFAULT NULL, LEGAL_FORM_ID BIGINT NOT NULL, INDEX IDX_60D6D4887FBA2340 (LEGAL_FORM_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE THUMBS (ID BIGINT AUTO_INCREMENT NOT NULL, PATH VARCHAR(255) NOT NULL, URL VARCHAR(255) NOT NULL, WIDTH INT NOT NULL, HEIGHT INT NOT NULL, IS_CROPPED TINYINT(1) NOT NULL, IS_ASPECT_RATIO_PRESERVED TINYINT(1) NOT NULL, IMAGE_ID BIGINT DEFAULT NULL, INDEX IDX_FAE23400C3DBFFC1 (IMAGE_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ADDRESSES (ID BIGINT AUTO_INCREMENT NOT NULL, STREET_ADDRESS LONGTEXT NOT NULL, LOCALITY_ID INT NOT NULL, INDEX IDX_2B086BF93DCCEE9A (LOCALITY_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE LEGAL_FORMS (ID BIGINT AUTO_INCREMENT NOT NULL, NAME VARCHAR(255) NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BRANDS (ID BIGINT AUTO_INCREMENT NOT NULL, NAME VARCHAR(255) NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE LOCALITIES (ID INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(150) NOT NULL, SIGNIFICANCE INT NOT NULL, AREA_NAME VARCHAR(255) DEFAULT NULL, COUNTRY_ID INT DEFAULT NULL, REGION_ID INT DEFAULT NULL, INDEX IDX_4A789DD6CAFD65AF (COUNTRY_ID), INDEX IDX_4A789DD6E4A9595A (REGION_ID), INDEX search_locality_idx (COUNTRY_ID, SIGNIFICANCE, NAME), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE REGIONS ADD CONSTRAINT FK_9D2287E9CAFD65AF FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICES ADD CONSTRAINT FK_EBC71FDE3DCCEE9A FOREIGN KEY (LOCALITY_ID) REFERENCES LOCALITIES (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICES ADD CONSTRAINT FK_EBC71FDEC3DBFFC1 FOREIGN KEY (IMAGE_ID) REFERENCES IMAGES (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICES ADD CONSTRAINT FK_EBC71FDEA4494109 FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICE_BRANDS ADD CONSTRAINT FK_CD537D348A7A94FD FOREIGN KEY (CAR_SERVICE_ID) REFERENCES CAR_SERVICES (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICE_BRANDS ADD CONSTRAINT FK_CD537D34BA8B0AA4 FOREIGN KEY (BRAND_ID) REFERENCES BRANDS (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICE_SERVICES ADD CONSTRAINT FK_82DDDEFA8A7A94FD FOREIGN KEY (CAR_SERVICE_ID) REFERENCES CAR_SERVICES (ID)');
        $this->addSql('ALTER TABLE CAR_SERVICE_SERVICES ADD CONSTRAINT FK_82DDDEFADE8EF239 FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES (ID)');
        $this->addSql('ALTER TABLE COMPANIES ADD CONSTRAINT FK_C686B4D53DCCEE9A FOREIGN KEY (LOCALITY_ID) REFERENCES LOCALITIES (ID)');
        $this->addSql('ALTER TABLE COMPANIES ADD CONSTRAINT FK_C686B4D5C3DBFFC1 FOREIGN KEY (IMAGE_ID) REFERENCES IMAGES (ID)');
        $this->addSql('ALTER TABLE COMPANIES ADD CONSTRAINT FK_C686B4D562CC2368 FOREIGN KEY (ORG_INFO_ID) REFERENCES ORGANIZATION_INFOS (ID)');
        $this->addSql('ALTER TABLE ORGANIZATION_INFOS ADD CONSTRAINT FK_60D6D4887FBA2340 FOREIGN KEY (LEGAL_FORM_ID) REFERENCES LEGAL_FORMS (ID)');
        $this->addSql('ALTER TABLE THUMBS ADD CONSTRAINT FK_FAE23400C3DBFFC1 FOREIGN KEY (IMAGE_ID) REFERENCES IMAGES (ID)');
        $this->addSql('ALTER TABLE ADDRESSES ADD CONSTRAINT FK_2B086BF93DCCEE9A FOREIGN KEY (LOCALITY_ID) REFERENCES LOCALITIES (ID)');
        $this->addSql('ALTER TABLE LOCALITIES ADD CONSTRAINT FK_4A789DD6CAFD65AF FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (ID)');
        $this->addSql('ALTER TABLE LOCALITIES ADD CONSTRAINT FK_4A789DD6E4A9595A FOREIGN KEY (REGION_ID) REFERENCES REGIONS (ID)');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE LOCALITIES DROP FOREIGN KEY FK_4A789DD6E4A9595A');
        $this->addSql('ALTER TABLE CAR_SERVICES DROP FOREIGN KEY FK_EBC71FDEC3DBFFC1');
        $this->addSql('ALTER TABLE COMPANIES DROP FOREIGN KEY FK_C686B4D5C3DBFFC1');
        $this->addSql('ALTER TABLE THUMBS DROP FOREIGN KEY FK_FAE23400C3DBFFC1');
        $this->addSql('ALTER TABLE CAR_SERVICE_SERVICES DROP FOREIGN KEY FK_82DDDEFADE8EF239');
        $this->addSql('ALTER TABLE CAR_SERVICE_BRANDS DROP FOREIGN KEY FK_CD537D348A7A94FD');
        $this->addSql('ALTER TABLE CAR_SERVICE_SERVICES DROP FOREIGN KEY FK_82DDDEFA8A7A94FD');
        $this->addSql('ALTER TABLE REGIONS DROP FOREIGN KEY FK_9D2287E9CAFD65AF');
        $this->addSql('ALTER TABLE LOCALITIES DROP FOREIGN KEY FK_4A789DD6CAFD65AF');
        $this->addSql('ALTER TABLE CAR_SERVICES DROP FOREIGN KEY FK_EBC71FDEA4494109');
        $this->addSql('ALTER TABLE COMPANIES DROP FOREIGN KEY FK_C686B4D562CC2368');
        $this->addSql('ALTER TABLE ORGANIZATION_INFOS DROP FOREIGN KEY FK_60D6D4887FBA2340');
        $this->addSql('ALTER TABLE CAR_SERVICE_BRANDS DROP FOREIGN KEY FK_CD537D34BA8B0AA4');
        $this->addSql('ALTER TABLE CAR_SERVICES DROP FOREIGN KEY FK_EBC71FDE3DCCEE9A');
        $this->addSql('ALTER TABLE COMPANIES DROP FOREIGN KEY FK_C686B4D53DCCEE9A');
        $this->addSql('ALTER TABLE ADDRESSES DROP FOREIGN KEY FK_2B086BF93DCCEE9A');
        $this->addSql('DROP TABLE REGIONS');
        $this->addSql('DROP TABLE IMAGES');
        $this->addSql('DROP TABLE SERVICES');
        $this->addSql('DROP TABLE CAR_SERVICES');
        $this->addSql('DROP TABLE CAR_SERVICE_BRANDS');
        $this->addSql('DROP TABLE CAR_SERVICE_SERVICES');
        $this->addSql('DROP TABLE COUNTRIES');
        $this->addSql('DROP TABLE COMPANIES');
        $this->addSql('DROP TABLE ORGANIZATION_INFOS');
        $this->addSql('DROP TABLE THUMBS');
        $this->addSql('DROP TABLE ADDRESSES');
        $this->addSql('DROP TABLE LEGAL_FORMS');
        $this->addSql('DROP TABLE BRANDS');
        $this->addSql('DROP TABLE LOCALITIES');
    }
}
