<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150921161307 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE REQUEST_SERVICES DROP FOREIGN KEY FK_7034BC311C43127F');
        $this->addSql('DROP TABLE REQUESTS');
        $this->addSql('DROP TABLE REQUEST_SERVICES');
        $this->addSql('ALTER TABLE IMAGES CHANGE ADDED_TIMESTAMP ADDED_TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE CAR_OWNER_REQUESTS ADD CAR_OWNER_DATE DATETIME DEFAULT NULL, ADD CAR_OWNER_TIME_PERIOD BIGINT DEFAULT NULL, DROP CAR_OWNER_START_TIME, DROP CAR_OWNER_END_TIME');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE REQUESTS (ID BIGINT AUTO_INCREMENT NOT NULL, NAME VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, DESCRIPTION LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, DIALOG_ID BIGINT DEFAULT NULL, COMPANY_ID BIGINT NOT NULL, CAR_OWNER_ID BIGINT NOT NULL, START_TIME DATETIME DEFAULT NULL, END_TIME DATETIME DEFAULT NULL, PHONE VARCHAR(50) DEFAULT NULL COLLATE utf8_unicode_ci, EMAIL VARCHAR(50) DEFAULT NULL COLLATE utf8_unicode_ci, ADDED_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CAR_ID BIGINT NOT NULL, INDEX IDX_BDB64A1DA4494109 (COMPANY_ID), INDEX IDX_BDB64A1DDE84D9AE (CAR_OWNER_ID), INDEX IDX_BDB64A1DB7377F9 (CAR_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE REQUEST_SERVICES (REQUEST_SERVICE_ID BIGINT NOT NULL, SERVICE_ID BIGINT NOT NULL, INDEX IDX_7034BC311C43127F (REQUEST_SERVICE_ID), INDEX IDX_7034BC31DE8EF239 (SERVICE_ID), PRIMARY KEY(REQUEST_SERVICE_ID, SERVICE_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE REQUESTS ADD CONSTRAINT FK_4D27185A4494109 FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES (ID)');
        $this->addSql('ALTER TABLE REQUESTS ADD CONSTRAINT FK_4D27185DE84D9AE FOREIGN KEY (CAR_OWNER_ID) REFERENCES CAR_OWNERS (ID)');
        $this->addSql('ALTER TABLE REQUESTS ADD CONSTRAINT FK_BDB64A1DB7377F9 FOREIGN KEY (CAR_ID) REFERENCES CARS (ID)');
        $this->addSql('ALTER TABLE REQUEST_SERVICES ADD CONSTRAINT FK_7034BC311C43127F FOREIGN KEY (REQUEST_SERVICE_ID) REFERENCES REQUESTS (ID)');
        $this->addSql('ALTER TABLE REQUEST_SERVICES ADD CONSTRAINT FK_7034BC31DE8EF239 FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES (ID)');
        $this->addSql('ALTER TABLE CAR_OWNER_REQUESTS ADD CAR_OWNER_START_TIME DATETIME DEFAULT NULL, CAR_OWNER_END_TIME DATETIME DEFAULT NULL, DROP CAR_OWNER_TIME_PERIOD');
    }
}
