<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150821131508 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE DIALOG (ID BIGINT AUTO_INCREMENT NOT NULL, RELATED_ENTITY VARCHAR(255) DEFAULT NULL, RELATED_ENTITY_ID BIGINT DEFAULT NULL, EXTENSIBLE TINYINT(1) DEFAULT NULL, UNIQUE_KEY VARCHAR(255) DEFAULT NULL, CREATION_TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, STATE_ID BIGINT NOT NULL, LAST_STATE_ID BIGINT NOT NULL, MESSAGES_COUNT INT NOT NULL, USER_ID BIGINT DEFAULT NULL, LAST_MESSAGE_ID BIGINT DEFAULT NULL, INDEX IDX_B5991FE4A0666B6F (USER_ID), INDEX IDX_B5991FE46732F457 (LAST_MESSAGE_ID), INDEX entity_lookup_idx (RELATED_ENTITY, RELATED_ENTITY_ID), UNIQUE INDEX DIALOG_UNIQUE_KEY_IDX (UNIQUE_KEY), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE DIALOG_PARTICIPANT (ID BIGINT AUTO_INCREMENT NOT NULL, UNREAD_COUNT INT NOT NULL, LAST_READ_MESSAGE_ID INT NOT NULL, STATE_ID BIGINT NOT NULL, DIALOG_ID BIGINT NOT NULL, USER_ID BIGINT DEFAULT NULL, INDEX IDX_4DF1656C22C99CED (DIALOG_ID), INDEX IDX_4DF1656CA0666B6F (USER_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MESSAGES (ID BIGINT AUTO_INCREMENT NOT NULL, GUID VARCHAR(255) NOT NULL COMMENT \'(DC2Type:guid)\', CREATED_TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, BODY LONGTEXT NOT NULL, STATE_ID BIGINT NOT NULL, USER_ID BIGINT DEFAULT NULL, DIALOG_ID BIGINT NOT NULL, INDEX IDX_1D3182DAA0666B6F (USER_ID), INDEX IDX_1D3182DA22C99CED (DIALOG_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MESSAGE_ATTACHMENT (ID BIGINT AUTO_INCREMENT NOT NULL, MESSAGE_ID BIGINT NOT NULL, TYPE VARCHAR(255) NOT NULL, INDEX IDX_3724CFE760A848F6 (MESSAGE_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MESSAGE_STATUS (ID BIGINT AUTO_INCREMENT NOT NULL, DELIVERED_TIMESTAMP timestamp NULL, READ_TIMESTAMP timestamp NULL, CURRENT_STATUS enum(\'new\', \'delivered\', \'read\') NOT NULL DEFAULT \'new\', STATE_ID BIGINT NOT NULL, USER_ID BIGINT DEFAULT NULL, MESSAGE_ID BIGINT NOT NULL, INDEX IDX_68B2BBB2A0666B6F (USER_ID), INDEX IDX_68B2BBB260A848F6 (MESSAGE_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE IMAGE_ATTACHMENT (IMAGE_ID BIGINT NOT NULL, ID BIGINT NOT NULL, INDEX IDX_E7CF7E84C3DBFFC1 (IMAGE_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE USERS (ID BIGINT AUTO_INCREMENT NOT NULL, TYPE enum(\'company\', \'car_owner\') NOT NULL DEFAULT \'car_owner\', PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE DIALOG ADD CONSTRAINT FK_B5991FE4A0666B6F FOREIGN KEY (USER_ID) REFERENCES USERS (ID)');
        $this->addSql('ALTER TABLE DIALOG ADD CONSTRAINT FK_B5991FE46732F457 FOREIGN KEY (LAST_MESSAGE_ID) REFERENCES MESSAGES (ID)');
        $this->addSql('ALTER TABLE DIALOG_PARTICIPANT ADD CONSTRAINT FK_4DF1656C22C99CED FOREIGN KEY (DIALOG_ID) REFERENCES DIALOG (ID)');
        $this->addSql('ALTER TABLE DIALOG_PARTICIPANT ADD CONSTRAINT FK_4DF1656CA0666B6F FOREIGN KEY (USER_ID) REFERENCES USERS (ID)');
        $this->addSql('ALTER TABLE MESSAGES ADD CONSTRAINT FK_1D3182DAA0666B6F FOREIGN KEY (USER_ID) REFERENCES USERS (ID)');
        $this->addSql('ALTER TABLE MESSAGES ADD CONSTRAINT FK_1D3182DA22C99CED FOREIGN KEY (DIALOG_ID) REFERENCES DIALOG (ID)');
        $this->addSql('ALTER TABLE MESSAGE_ATTACHMENT ADD CONSTRAINT FK_3724CFE760A848F6 FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGES (ID)');
        $this->addSql('ALTER TABLE MESSAGE_STATUS ADD CONSTRAINT FK_68B2BBB2A0666B6F FOREIGN KEY (USER_ID) REFERENCES USERS (ID)');
        $this->addSql('ALTER TABLE MESSAGE_STATUS ADD CONSTRAINT FK_68B2BBB260A848F6 FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGES (ID)');
        $this->addSql('ALTER TABLE IMAGE_ATTACHMENT ADD CONSTRAINT FK_E7CF7E84C3DBFFC1 FOREIGN KEY (IMAGE_ID) REFERENCES IMAGES (ID)');
        $this->addSql('ALTER TABLE IMAGE_ATTACHMENT ADD CONSTRAINT FK_E7CF7E8411D3633A FOREIGN KEY (ID) REFERENCES MESSAGE_ATTACHMENT (ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE COMPANIES ADD USER_ID BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE COMPANIES ADD CONSTRAINT FK_C686B4D5A0666B6F FOREIGN KEY (USER_ID) REFERENCES USERS (ID)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C686B4D5A0666B6F ON COMPANIES (USER_ID)');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE DIALOG_PARTICIPANT DROP FOREIGN KEY FK_4DF1656C22C99CED');
        $this->addSql('ALTER TABLE MESSAGES DROP FOREIGN KEY FK_1D3182DA22C99CED');
        $this->addSql('ALTER TABLE DIALOG DROP FOREIGN KEY FK_B5991FE46732F457');
        $this->addSql('ALTER TABLE MESSAGE_ATTACHMENT DROP FOREIGN KEY FK_3724CFE760A848F6');
        $this->addSql('ALTER TABLE MESSAGE_STATUS DROP FOREIGN KEY FK_68B2BBB260A848F6');
        $this->addSql('ALTER TABLE IMAGE_ATTACHMENT DROP FOREIGN KEY FK_E7CF7E8411D3633A');
        $this->addSql('ALTER TABLE DIALOG DROP FOREIGN KEY FK_B5991FE4A0666B6F');
        $this->addSql('ALTER TABLE DIALOG_PARTICIPANT DROP FOREIGN KEY FK_4DF1656CA0666B6F');
        $this->addSql('ALTER TABLE MESSAGES DROP FOREIGN KEY FK_1D3182DAA0666B6F');
        $this->addSql('ALTER TABLE MESSAGE_STATUS DROP FOREIGN KEY FK_68B2BBB2A0666B6F');
        $this->addSql('ALTER TABLE COMPANIES DROP FOREIGN KEY FK_C686B4D5A0666B6F');
        $this->addSql('DROP TABLE DIALOG');
        $this->addSql('DROP TABLE DIALOG_PARTICIPANT');
        $this->addSql('DROP TABLE MESSAGES');
        $this->addSql('DROP TABLE MESSAGE_ATTACHMENT');
        $this->addSql('DROP TABLE MESSAGE_STATUS');
        $this->addSql('DROP TABLE IMAGE_ATTACHMENT');
        $this->addSql('DROP TABLE USERS');
        $this->addSql('DROP INDEX UNIQ_C686B4D5A0666B6F ON COMPANIES');
        $this->addSql('ALTER TABLE COMPANIES DROP USER_ID');
    }
}
