<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160609172932 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE TARIFFS (ID BIGINT AUTO_INCREMENT NOT NULL, NAME VARCHAR(255) NOT NULL, DESCRIPTION LONGTEXT DEFAULT NULL, IS_ACTIVE TINYINT(1) NOT NULL, CREATED_TIMESTAMP DATETIME NOT NULL, SERVICE_ID BIGINT DEFAULT NULL, INDEX IDX_A6B59B0DE8EF239 (SERVICE_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BILLING_SERVICES (ID BIGINT AUTO_INCREMENT NOT NULL, NAME VARCHAR(255) NOT NULL, DESCRIPTION LONGTEXT DEFAULT NULL, IS_PERIODIC TINYINT(1) NOT NULL, PRICE NUMERIC(10, 2) NULL, CREATED_TIMESTAMP DATETIME NOT NULL, CATEGORY_ID BIGINT DEFAULT NULL, INDEX IDX_9DCD35E8A70849EA (CATEGORY_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE INVOICES (ID BIGINT AUTO_INCREMENT NOT NULL, DESCRIPTION VARCHAR(255) NOT NULL, IS_PAID TINYINT(1) NOT NULL, SUM NUMERIC(10, 2) NOT NULL, CREATED_TIMESTAMP DATETIME NOT NULL, USER_ID BIGINT NOT NULL, AGENT_ID INT DEFAULT NULL, ORDERED_SERVICE_ID BIGINT DEFAULT NULL, INDEX IDX_AC1CB3D9A0666B6F (USER_ID), INDEX IDX_AC1CB3D9CA6AABA7 (AGENT_ID), INDEX IDX_AC1CB3D935111A2A (ORDERED_SERVICE_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE PRICES (ID BIGINT AUTO_INCREMENT NOT NULL, PERIOD VARCHAR(10) DEFAULT NULL, PRICE NUMERIC(10, 2) NOT NULL, START_DATE DATETIME DEFAULT NULL, END_DATE DATETIME DEFAULT NULL, IS_ACTIVE TINYINT(1) NOT NULL, CREATED_TIMESTAMP DATETIME NOT NULL, SERVICE_ID BIGINT DEFAULT NULL, TARIFF_ID BIGINT DEFAULT NULL, INDEX IDX_1433AADFDE8EF239 (SERVICE_ID), INDEX IDX_1433AADFEEBBD7DD (TARIFF_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BALANCES (ID BIGINT AUTO_INCREMENT NOT NULL, INCOME NUMERIC(10, 2) DEFAULT NULL, EXPENSE NUMERIC(10, 2) DEFAULT NULL, CREATED_TIMESTAMP DATETIME NOT NULL, USER_ID BIGINT DEFAULT NULL, PAYMENT_ID BIGINT DEFAULT NULL, CHARGE_ID BIGINT DEFAULT NULL, INDEX IDX_87947843A0666B6F (USER_ID), INDEX IDX_879478433711F864 (PAYMENT_ID), INDEX IDX_8794784329A7111B (CHARGE_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BILLING_SERVICE_CATEGORIES (ID BIGINT AUTO_INCREMENT NOT NULL, NAME VARCHAR(255) NOT NULL, DESCRIPTION LONGTEXT DEFAULT NULL, CREATED_TIMESTAMP DATETIME NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CHARGES (ID BIGINT AUTO_INCREMENT NOT NULL, CREATED_TIMESTAMP DATETIME NOT NULL, ORDERED_SERVICE_ID BIGINT NOT NULL, USER_ID BIGINT NOT NULL, INDEX IDX_5AAAE0035111A2A (ORDERED_SERVICE_ID), INDEX IDX_5AAAE00A0666B6F (USER_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ORDERED_SERVICES (ID BIGINT AUTO_INCREMENT NOT NULL, START_DATE DATETIME DEFAULT NULL, END_DATE DATETIME DEFAULT NULL, STATUS VARCHAR(20) NOT NULL, CREATED_TIMESTAMP DATETIME NOT NULL, SERVICE_ID BIGINT NOT NULL, PRICE_ID BIGINT NOT NULL, SUBSCRIBED_SERVICE_ID BIGINT DEFAULT NULL, USER_ID BIGINT NOT NULL, INDEX IDX_F412F6BDE8EF239 (SERVICE_ID), INDEX IDX_F412F6B24414939 (SUBSCRIBED_SERVICE_ID), INDEX IDX_F412F6BA0666B6F (USER_ID), INDEX IDX_F412F6B286A1D4B (PRICE_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SUBSCRIBED_SERVICES (ID BIGINT AUTO_INCREMENT NOT NULL, IS_AUTO_RENEWAL TINYINT(1) NOT NULL, STATUS VARCHAR(20) NOT NULL, CREATED_TIMESTAMP DATETIME NOT NULL, SERVICE_ID BIGINT NOT NULL, PRICE_ID BIGINT NOT NULL, USER_ID BIGINT NOT NULL, INDEX IDX_890ECE5ADE8EF239 (SERVICE_ID), INDEX IDX_890ECE5A286A1D4B (PRICE_ID), INDEX IDX_890ECE5AA0666B6F (USER_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE PAYMENT_INVOICES (ID BIGINT AUTO_INCREMENT NOT NULL, SUM NUMERIC(10, 2) DEFAULT NULL, CREATED_TIMESTAMP DATETIME NOT NULL, PAYMENT_ID BIGINT DEFAULT NULL, INVOICE_ID BIGINT DEFAULT NULL, INDEX IDX_DCCAD0803711F864 (PAYMENT_ID), INDEX IDX_DCCAD0801A5BAA22 (INVOICE_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE PAYMENTS (ID BIGINT AUTO_INCREMENT NOT NULL, DESCRIPTION VARCHAR(255) NOT NULL, CREATED_TIMESTAMP DATETIME NOT NULL, USER_ID BIGINT DEFAULT NULL, PAY_DATE DATETIME NOT NULL, SUM NUMERIC(10, 2) NOT NULL, INDEX IDX_A3E1077EA0666B6F (USER_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE TARIFFS ADD CONSTRAINT FK_A6B59B0DE8EF239 FOREIGN KEY (SERVICE_ID) REFERENCES BILLING_SERVICES (ID)');
        $this->addSql('ALTER TABLE BILLING_SERVICES ADD CONSTRAINT FK_9DCD35E8A70849EA FOREIGN KEY (CATEGORY_ID) REFERENCES BILLING_SERVICE_CATEGORIES (ID)');
        $this->addSql('ALTER TABLE INVOICES ADD CONSTRAINT FK_AC1CB3D9A0666B6F FOREIGN KEY (USER_ID) REFERENCES USERS (ID)');
        $this->addSql('ALTER TABLE INVOICES ADD CONSTRAINT FK_AC1CB3D9CA6AABA7 FOREIGN KEY (AGENT_ID) REFERENCES AGENTS (ID)');
        $this->addSql('ALTER TABLE INVOICES ADD CONSTRAINT FK_AC1CB3D935111A2A FOREIGN KEY (ORDERED_SERVICE_ID) REFERENCES ORDERED_SERVICES (ID)');
        $this->addSql('ALTER TABLE PRICES ADD CONSTRAINT FK_1433AADFDE8EF239 FOREIGN KEY (SERVICE_ID) REFERENCES BILLING_SERVICES (ID)');
        $this->addSql('ALTER TABLE PRICES ADD CONSTRAINT FK_1433AADFEEBBD7DD FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS (ID)');
        $this->addSql('ALTER TABLE BALANCES ADD CONSTRAINT FK_87947843A0666B6F FOREIGN KEY (USER_ID) REFERENCES USERS (ID)');
        $this->addSql('ALTER TABLE BALANCES ADD CONSTRAINT FK_879478433711F864 FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENTS (ID)');
        $this->addSql('ALTER TABLE BALANCES ADD CONSTRAINT FK_8794784329A7111B FOREIGN KEY (CHARGE_ID) REFERENCES CHARGES (ID)');
        $this->addSql('ALTER TABLE CHARGES ADD CONSTRAINT FK_5AAAE0035111A2A FOREIGN KEY (ORDERED_SERVICE_ID) REFERENCES ORDERED_SERVICES (ID)');
        $this->addSql('ALTER TABLE CHARGES ADD CONSTRAINT FK_5AAAE00A0666B6F FOREIGN KEY (USER_ID) REFERENCES USERS (ID)');
        $this->addSql('ALTER TABLE ORDERED_SERVICES ADD CONSTRAINT FK_F412F6BDE8EF239 FOREIGN KEY (SERVICE_ID) REFERENCES BILLING_SERVICES (ID)');
        $this->addSql('ALTER TABLE ORDERED_SERVICES ADD CONSTRAINT FK_F412F6B24414939 FOREIGN KEY (SUBSCRIBED_SERVICE_ID) REFERENCES SUBSCRIBED_SERVICES (ID)');
        $this->addSql('ALTER TABLE ORDERED_SERVICES ADD CONSTRAINT FK_F412F6BA0666B6F FOREIGN KEY (USER_ID) REFERENCES USERS (ID)');
        $this->addSql('ALTER TABLE ORDERED_SERVICES ADD CONSTRAINT FK_F412F6B286A1D4B FOREIGN KEY (PRICE_ID) REFERENCES PRICES (ID)');
        $this->addSql('ALTER TABLE SUBSCRIBED_SERVICES ADD CONSTRAINT FK_890ECE5ADE8EF239 FOREIGN KEY (SERVICE_ID) REFERENCES BILLING_SERVICES (ID)');
        $this->addSql('ALTER TABLE SUBSCRIBED_SERVICES ADD CONSTRAINT FK_890ECE5A286A1D4B FOREIGN KEY (PRICE_ID) REFERENCES PRICES (ID)');
        $this->addSql('ALTER TABLE SUBSCRIBED_SERVICES ADD CONSTRAINT FK_890ECE5AA0666B6F FOREIGN KEY (USER_ID) REFERENCES USERS (ID)');
        $this->addSql('ALTER TABLE PAYMENT_INVOICES ADD CONSTRAINT FK_DCCAD0803711F864 FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENTS (ID)');
        $this->addSql('ALTER TABLE PAYMENT_INVOICES ADD CONSTRAINT FK_DCCAD0801A5BAA22 FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES (ID)');
        $this->addSql('ALTER TABLE PAYMENTS ADD CONSTRAINT FK_A3E1077EA0666B6F FOREIGN KEY (USER_ID) REFERENCES USERS (ID)');
        $this->addSql('ALTER TABLE USERS ADD BALANCE NUMERIC(10, 2) NOT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE PRICES DROP FOREIGN KEY FK_1433AADFEEBBD7DD');
        $this->addSql('ALTER TABLE TARIFFS DROP FOREIGN KEY FK_A6B59B0DE8EF239');
        $this->addSql('ALTER TABLE PRICES DROP FOREIGN KEY FK_1433AADFDE8EF239');
        $this->addSql('ALTER TABLE ORDERED_SERVICES DROP FOREIGN KEY FK_F412F6BDE8EF239');
        $this->addSql('ALTER TABLE SUBSCRIBED_SERVICES DROP FOREIGN KEY FK_890ECE5ADE8EF239');
        $this->addSql('ALTER TABLE SUBSCRIBED_SERVICES DROP FOREIGN KEY FK_890ECE5A286A1D4B');
        $this->addSql('ALTER TABLE BILLING_SERVICES DROP FOREIGN KEY FK_9DCD35E8A70849EA');
        $this->addSql('ALTER TABLE BALANCES DROP FOREIGN KEY FK_8794784329A7111B');
        $this->addSql('ALTER TABLE CHARGES DROP FOREIGN KEY FK_5AAAE0035111A2A');
        $this->addSql('ALTER TABLE ORDERED_SERVICES DROP FOREIGN KEY FK_F412F6B24414939');
        $this->addSql('ALTER TABLE ORDERED_SERVICES DROP FOREIGN KEY FK_F412F6B286A1D4B');
        $this->addSql('ALTER TABLE BALANCES DROP FOREIGN KEY FK_879478433711F864');
        $this->addSql('ALTER TABLE INVOICES DROP FOREIGN KEY FK_AC1CB3D935111A2A');
        $this->addSql('ALTER TABLE PAYMENT_INVOICES DROP FOREIGN KEY FK_DCCAD0803711F864');
        $this->addSql('ALTER TABLE PAYMENT_INVOICES DROP FOREIGN KEY FK_DCCAD0801A5BAA22');
        $this->addSql('DROP TABLE TARIFFS');
        $this->addSql('DROP TABLE BILLING_SERVICES');
        $this->addSql('DROP TABLE INVOICES');
        $this->addSql('DROP TABLE PRICES');
        $this->addSql('DROP TABLE BALANCES');
        $this->addSql('DROP TABLE BILLING_SERVICE_CATEGORIES');
        $this->addSql('DROP TABLE CHARGES');
        $this->addSql('DROP TABLE ORDERED_SERVICES');
        $this->addSql('DROP TABLE SUBSCRIBED_SERVICES');
        $this->addSql('DROP TABLE PAYMENT_INVOICES');
        $this->addSql('DROP TABLE PAYMENTS');
        $this->addSql('ALTER TABLE USERS DROP BALANCE');
    }
}
